export const STEELCROSS_MARKET_SHOP_GOODS_DEFS = Object.freeze({
  good_food_hard_card: Object.freeze({
    id: "good_food_hard_card",
    name: "好食硬卡",
    price: 8,
    purchaseEnabled: true,
    purchaseMode: "instant_consume",
    itemId: "good_food_hard_card",
    tags: Object.freeze(["热饮", "即时饮用", "好食味"]),
    description: "纸杯里装着一杯说不清来路的深色热饮，热可可的香气顺着白雾往外散。码头上不少人都认这个味，手里捧一会儿，连胸口都跟着暖起来。",
    icon: "cup_noodles",
    order: 300
  }),
  material_rough_cloth: Object.freeze({
    id: "material_rough_cloth",
    name: "粗布",
    price: 150,
    purchaseEnabled: true,
    tags: Object.freeze(["material", "固定货", "补丁铺常备"]),
    description: "你用不上这个。",
    icon: "utility_bundle",
    inventoryItemId: "material_rough_cloth",
    order: 310
  }),
  cloth_patterned_wool_scarf: Object.freeze({
    id: "cloth_patterned_wool_scarf",
    name: "印花羊毛围脖",
    price: 158,
    purchaseEnabled: true,
    tags: Object.freeze(["clothing", "颈部", "中概率"]),
    description: "旧羊毛织得很密，印花已经洗淡了，缠上之后脖颈一圈能稳稳拢住热气。",
    icon: "old_scarf",
    inventoryItemId: "cloth_patterned_wool_scarf",
    order: 320
  }),
  cloth_old_cowhide_gloves: Object.freeze({
    id: "cloth_old_cowhide_gloves",
    name: "旧牛皮手套",
    price: 162,
    purchaseEnabled: true,
    tags: Object.freeze(["clothing", "手部", "中概率"]),
    description: "皮面磨出了细纹，掌心却还结实，挡风比一般布手套要实在得多。",
    icon: "thin_gloves",
    inventoryItemId: "cloth_old_cowhide_gloves",
    order: 330
  }),
  cloth_knit_cap_patchshop: Object.freeze({
    id: "cloth_knit_cap_patchshop",
    name: "针织帽",
    price: 168,
    purchaseEnabled: true,
    tags: Object.freeze(["clothing", "头部", "中概率"]),
    description: "帽身织得厚，边沿收口也紧，压住耳侧以后，冷风不太容易直接灌进去。",
    icon: "knit_cap",
    inventoryItemId: "cloth_knit_cap_patchshop",
    order: 340
  }),
  cloth_graygreen_polycotton_workwear: Object.freeze({
    id: "cloth_graygreen_polycotton_workwear",
    name: "灰绿涤棉工装",
    price: 186,
    purchaseEnabled: true,
    tags: Object.freeze(["clothing", "上装", "中概率"]),
    description: "涤棉面料耐磨耐脏，颜色洗得发灰，穿在最外层倒还很像回事。",
    icon: "utility_bundle",
    inventoryItemId: "cloth_graygreen_polycotton_workwear",
    order: 350
  }),
  cloth_canvas_backpack_patchshop: Object.freeze({
    id: "cloth_canvas_backpack_patchshop",
    name: "帆布背包",
    price: 152,
    purchaseEnabled: true,
    tags: Object.freeze(["clothing", "背包", "中概率"]),
    description: "帆布压得厚，肩带和扣件也都还能用，装点零碎出门不成问题。",
    icon: "utility_bundle",
    inventoryItemId: "cloth_canvas_backpack_patchshop",
    order: 360
  }),
  cloth_thick_fleece_trousers: Object.freeze({
    id: "cloth_thick_fleece_trousers",
    name: "厚抓绒裤",
    price: 178,
    purchaseEnabled: true,
    tags: Object.freeze(["clothing", "下装", "低概率"]),
    description: "裤料内侧压着一层厚抓绒，走在风里时，腿上那层冷意会慢很多。",
    icon: "utility_bundle",
    inventoryItemId: "cloth_thick_fleece_trousers",
    order: 370
  }),
  cloth_snowfield_boots: Object.freeze({
    id: "cloth_snowfield_boots",
    name: "雪地靴",
    price: 192,
    purchaseEnabled: true,
    tags: Object.freeze(["clothing", "鞋", "低概率"]),
    description: "靴帮高，鞋底也厚，踩在雪地里不算轻，但脚上能稳稳保住温度。",
    icon: "utility_bundle",
    inventoryItemId: "cloth_snowfield_boots",
    order: 380
  }),
  cloth_quilted_inner_lining: Object.freeze({
    id: "cloth_quilted_inner_lining",
    name: "加厚内衬",
    price: 166,
    purchaseEnabled: true,
    tags: Object.freeze(["clothing", "内衬", "低概率"]),
    description: "里层缝得密，贴身那一面压得更厚，穿进去以后整套衣服都会安稳一些。",
    icon: "utility_bundle",
    inventoryItemId: "cloth_quilted_inner_lining",
    order: 390
  }),
  consumable_compressed_biscuits: Object.freeze({
    id: "consumable_compressed_biscuits",
    name: "压缩饼干",
    price: 12,
    purchaseEnabled: true,
    tags: Object.freeze(["consumable", "杂货", "常见"]),
    description: "结实耐放，掰开就能顶一阵。",
    icon: "utility_bundle",
    inventoryItemId: "consumable_compressed_biscuits",
    order: 210
  }),
  consumable_canned_fish: Object.freeze({
    id: "consumable_canned_fish",
    name: "鱼罐头",
    price: 18,
    purchaseEnabled: true,
    tags: Object.freeze(["consumable", "杂货", "常见"]),
    description: "小铁罐封得紧，开盖就是一顿。",
    icon: "utility_bundle",
    inventoryItemId: "consumable_canned_fish",
    order: 220
  }),
  consumable_canned_luncheon_meat: Object.freeze({
    id: "consumable_canned_luncheon_meat",
    name: "午餐肉罐头",
    price: 22,
    purchaseEnabled: true,
    tags: Object.freeze(["consumable", "杂货", "常见"]),
    description: "分量扎实，开罐后油盐味很直接。",
    icon: "utility_bundle",
    inventoryItemId: "consumable_canned_luncheon_meat",
    order: 230
  }),
  consumable_chocolate_bar: Object.freeze({
    id: "consumable_chocolate_bar",
    name: "巧克力条",
    price: 10,
    purchaseEnabled: true,
    tags: Object.freeze(["consumable", "杂货", "常见"]),
    description: "甜味来得快，揣口袋里也方便。",
    icon: "utility_bundle",
    inventoryItemId: "consumable_chocolate_bar",
    order: 240
  }),
  consumable_instant_oat_cup: Object.freeze({
    id: "consumable_instant_oat_cup",
    name: "速食燕麦杯",
    price: 16,
    purchaseEnabled: true,
    tags: Object.freeze(["consumable", "杂货", "常见"]),
    description: "热水一冲就能下肚，胜在稳当。",
    icon: "cup_noodles",
    inventoryItemId: "consumable_instant_oat_cup",
    order: 250
  }),
  tool_lighter: Object.freeze({
    id: "tool_lighter",
    name: "打火机",
    price: 26,
    purchaseEnabled: true,
    tags: Object.freeze(["tool", "火种", "偶见"]),
    description: "常见的小火源工具，揣在口袋里不占地方。",
    icon: "utility_bundle",
    inventoryItemId: "tool_lighter",
    order: 260
  }),
  tool_pocket_watch: Object.freeze({
    id: "tool_pocket_watch",
    name: "怀表",
    price: 32,
    purchaseEnabled: true,
    tags: Object.freeze(["tool", "时间", "偶见"]),
    description: "能看准时间的旧式怀表，盖壳和链子还算完整。",
    icon: "utility_bundle",
    inventoryItemId: "tool_pocket_watch",
    order: 270
  }),
  doc_researcher_manuscript: Object.freeze({
    id: "doc_researcher_manuscript",
    name: "研究员的手稿",
    price: 48,
    purchaseEnabled: true,
    tags: Object.freeze(["文稿", "一次性", "稀有"]),
    description: "一份夹着批注和修订痕迹的手稿。",
    icon: "pill_box",
    inventoryItemId: "doc_researcher_manuscript",
    order: 280
  }),
  dried_small_fish: Object.freeze({
    id: "dried_small_fish",
    name: "风干小鱼",
    price: 22,
    purchaseEnabled: true,
    tags: Object.freeze(["consumable", "鱼货", "常见"]),
    description: "干、咸、耐放，拿回去嚼不算亏。",
    icon: "utility_bundle",
    inventoryItemId: "consumable_dried_small_fish",
    order: 110
  }),
  salted_fish_slices: Object.freeze({
    id: "salted_fish_slices",
    name: "盐渍鱼片",
    price: 28,
    purchaseEnabled: true,
    tags: Object.freeze(["consumable", "鱼货", "常见"]),
    description: "处理过的鱼肉片，咸味压得住寒气。",
    icon: "utility_bundle",
    inventoryItemId: "consumable_salted_fish_slices",
    order: 120
  }),
  frozen_silverside_bundle: Object.freeze({
    id: "frozen_silverside_bundle",
    name: "冻银鱼包",
    price: 30,
    purchaseEnabled: true,
    tags: Object.freeze(["consumable", "鱼货", "常见"]),
    description: "一小包码好的银鱼，边缘还结着霜。",
    icon: "utility_bundle",
    inventoryItemId: "consumable_frozen_silverside_bundle",
    order: 130
  }),
  iced_whole_fish: Object.freeze({
    id: "iced_whole_fish",
    name: "冰鲜整鱼",
    price: 40,
    purchaseEnabled: true,
    tags: Object.freeze(["consumable", "鱼货", "稀有"]),
    description: "今天刚上岸的整鱼，摊面上只摆了一条。",
    icon: "utility_bundle",
    inventoryItemId: "consumable_iced_whole_fish",
    order: 140
  }),
  fresh_cut_fish_fillets: Object.freeze({
    id: "fresh_cut_fish_fillets",
    name: "现剖鱼片",
    price: 38,
    purchaseEnabled: true,
    tags: Object.freeze(["consumable", "鱼货", "稀有"]),
    description: "现剖出来的鱼片，刀口还新。",
    icon: "utility_bundle",
    inventoryItemId: "consumable_fresh_cut_fish_fillets",
    order: 150
  }),
  iced_silverside_bundle: Object.freeze({
    id: "iced_silverside_bundle",
    name: "冰鲜银鱼包",
    price: 34,
    purchaseEnabled: true,
    tags: Object.freeze(["consumable", "鱼货", "稀有"]),
    description: "比常见那包更鲜，也更少。",
    icon: "utility_bundle",
    inventoryItemId: "consumable_iced_silverside_bundle",
    order: 160
  }),
  roe_small_box: Object.freeze({
    id: "roe_small_box",
    name: "小盒鱼卵",
    price: 42,
    purchaseEnabled: true,
    tags: Object.freeze(["consumable", "鱼货", "稀有"]),
    description: "小盒装着，量不多，懂行的才会多看两眼。",
    icon: "pill_box",
    inventoryItemId: "consumable_roe_small_box",
    order: 170
  }),
  fish_liver_pack: Object.freeze({
    id: "fish_liver_pack",
    name: "鱼肝小包",
    price: 35,
    purchaseEnabled: true,
    tags: Object.freeze(["consumable", "鱼货", "稀有"]),
    description: "腥味重，但热量也实在。",
    icon: "utility_bundle",
    inventoryItemId: "consumable_fish_liver_pack",
    order: 180
  })
});